# Generated by Django 5.1 on 2024-09-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_alter_user_first_name_alter_user_last_name_bid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="bid",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="comments",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="listing_id",
        ),
        migrations.AddField(
            model_name="listing",
            name="start_bid",
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
            preserve_default=False,
        ),
    ]
