# Generated by Django 5.1 on 2024-09-10 14:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_remove_listing_bid_remove_listing_comments_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bid",
            options={"ordering": ["-amount"]},
        ),
        migrations.RenameField(
            model_name="bid",
            old_name="price",
            new_name="amount",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="text",
            new_name="content",
        ),
        migrations.RenameField(
            model_name="listing",
            old_name="start_bid",
            new_name="starting_bid",
        ),
        migrations.RenameField(
            model_name="listing",
            old_name="name",
            new_name="title",
        ),
        migrations.RemoveField(
            model_name="bid",
            name="user",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="user",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="image",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="price",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="user",
        ),
        migrations.AddField(
            model_name="bid",
            name="auction",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bids",
                to="auctions.listing",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bid",
            name="bidder",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bids",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comment",
            name="auction",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="auctions.listing",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comment",
            name="commenter",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="listing",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listings",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="bid",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="comment",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="listing",
            name="category",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="listing",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
